version: '3.9'
services:
  frontend:
    container_name: app_frontend
    build: ./frontend
    ports:
      - "3000:3000"
    working_dir: /frontend
    depends_on:
      - backend
  
  backend:
    container_name: app_backend
    build: ./backend
    ports:
      - "3001:3001"
    working_dir: /backend
    volumes:
      - ./backend/src:backend/src
    depends_on:
      - database
  
  database:
    container_name: app_database
    image: mysql:8.4.2
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
